#!/bin/sh

    # Change the next 3 lines to suit where you install your script and what you want to call it
    DAEMON_NAME=turret

    case "$1" in
            start)
                    /usr/bin/python3 /home/pi/dev/turret/motor.py > /dev/null &
                    ;;

            *)

            echo "Usage: /etc/init.d/$DEAMON_NAME {start}"
            exit 1
            ;;
    esac
    
